// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDK766grupywZXlbFA5EZH4ze3Zil0IPU',
    appId: '1:234714823287:web:2a0c5004f1517980526472',
    messagingSenderId: '234714823287',
    projectId: 'firebase-chat-app-viajus',
    authDomain: 'fir-chat-app-viajus.firebaseapp.com',
    storageBucket: 'firebase-chat-app-viajus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpKZSvU4ZJG-zj8uAO7dVWbqV7w6P2O-U',
    appId: '1:234714823287:android:0617f210b025baaa526472',
    messagingSenderId: '234714823287',
    projectId: 'firebase-chat-app-viajus',
    storageBucket: 'firebase-chat-app-viajus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB0go6c-aZqCEY0DZ8NYK7rooCnh0mGAA',
    appId: '1:234714823287:ios:86a472db120cb4d4526472',
    messagingSenderId: '234714823287',
    projectId: 'firebase-chat-app-viajus',
    storageBucket: 'firebase-chat-app-viajus.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB0go6c-aZqCEY0DZ8NYK7rooCnh0mGAA',
    appId: '1:234714823287:ios:8411842189472162526472',
    messagingSenderId: '234714823287',
    projectId: 'firebase-chat-app-viajus',
    storageBucket: 'firebase-chat-app-viajus.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
